variables:
  MKL_IMAGE: ghcr.io/ricosjp/allgebra/cuda10_1/clang11gcc7/mkl:21.05.0
  OSS_IMAGE: ghcr.io/ricosjp/allgebra/cuda10_1/clang11gcc7/oss:21.05.0

before_script:
    - export MONOLISH_DIR="${CI_PROJECT_DIR}/${PREFIX}"
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib:/usr/local/lib/

stages:
    - build_lib
    - test
    - python
    - benchmark
    - deploy

# gpu mkl
.gpu_avx_clang_mkl:
    variables:
        PREFIX: "gpu_avx"
        TEST_TARGET: "gpu"
        MONOLISH_USE_GPU: "ON"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.1/bin/clang"
        CXX: "/usr/local/llvm-11.0.1/bin/clang++"
    tags:
        - gpu
        - nvidia0-sm_61
        - avx
    image: ${MKL_IMAGE}

.gpu_noavx_clang_mkl:
    variables:
        PREFIX: "gpu_noavx"
        TEST_TARGET: "gpu"
        MONOLISH_USE_GPU: "ON"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.1/bin/clang"
        CXX: "/usr/local/llvm-11.0.1/bin/clang++"
    tags:
        - gpu
        - nvidia0-sm_61
    image: ${MKL_IMAGE}

# cpu mkl
.nogpu_avx_clang_mkl:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.1/bin/clang"
        CXX: "/usr/local/llvm-11.0.1/bin/clang++"
    tags:
        - avx
    image: ${MKL_IMAGE}

.nogpu_noavx_clang_mkl:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.1/bin/clang"
        CXX: "/usr/local/llvm-11.0.1/bin/clang++"
    image: ${MKL_IMAGE}

.nogpu_avx_gcc_mkl:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    tags:
        - avx
    image: ${MKL_IMAGE}

.nogpu_noavx_gcc_mkl:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    image: ${MKL_IMAGE}

# cpu oss
.nogpu_avx_clang_oss:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.1/bin/clang"
        CXX: "/usr/local/llvm-11.0.1/bin/clang++"
    tags:
        - avx
    image: ${OSS_IMAGE}

.nogpu_noavx_clang_oss:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.1/bin/clang"
        CXX: "/usr/local/llvm-11.0.1/bin/clang++"
    image: ${OSS_IMAGE}

.nogpu_avx_gcc_oss:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    tags:
        - avx
    image: ${OSS_IMAGE}

.nogpu_noavx_gcc_oss:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    image: ${OSS_IMAGE}

#
# Build stage
#
.build_cmake:
    stage: build_lib
    script:
        - cmake -Bbuild . -DMONOLISH_USE_GPU=${MONOLISH_USE_GPU} -DMONOLISH_USE_AVX=${MONOLISH_USE_AVX} -DCMAKE_INSTALL_PREFIX=${MONOLISH_DIR}
        - cmake --build build --target install -- -j $(nproc) VERBOSE=1
        - make -C test -j $(nproc) ${TEST_TARGET}
    artifacts:
        paths:
            - ${PREFIX}
            - test/
        expire_in: 360min

# gpu mkl
gpu_avx_clang_mkl_build_cmake:
    extends:
      - .gpu_avx_clang_mkl
      - .build_cmake
gpu_noavx_clang_mkl_build_cmake:
    extends:
      - .gpu_noavx_clang_mkl
      - .build_cmake
# cpu mkl
nogpu_avx_clang_mkl_build_cmake:
    extends:
      - .nogpu_avx_clang_mkl
      - .build_cmake
nogpu_noavx_clang_mkl_build_cmake:
    extends:
      - .nogpu_noavx_clang_mkl
      - .build_cmake
nogpu_avx_gcc_mkl_build_cmake:
    extends:
      - .nogpu_avx_gcc_mkl
      - .build_cmake
nogpu_noavx_gcc_mkl_build_cmake:
    extends:
      - .nogpu_noavx_gcc_mkl
      - .build_cmake
# cpu oss
nogpu_avx_clang_oss_build_cmake:
    extends:
      - .nogpu_avx_clang_oss
      - .build_cmake
nogpu_noavx_clang_oss_build_cmake:
    extends:
      - .nogpu_noavx_clang_oss
      - .build_cmake
nogpu_avx_gcc_oss_build_cmake:
    extends:
      - .nogpu_avx_gcc_oss
      - .build_cmake
nogpu_noavx_gcc_oss_build_cmake:
    extends:
      - .nogpu_noavx_gcc_oss
      - .build_cmake

MPI_build_test:
  stage: build_lib
  script:
    - make install_all
    - cd test/mpi; make clean; make -j; make run
  image: ${MKL_IMAGE}
  tags:
    - gpu
    - nvidia0-sm_52
    - avx

#
# Test Stage
#
.test:
  stage: test
  artifacts:
    paths:
      - test/logger/logging
    expire_in: 360min
    when: always

# gpu mkl
gpu_avx_clang_mkl:
    extends:
      - .gpu_avx_clang_mkl
      - .test
    needs:
      - "gpu_avx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_gpu

gpu_noavx_clang_mkl:
    extends:
      - .gpu_noavx_clang_mkl
      - .test
    needs:
      - "gpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_gpu

# cpu mkl
nogpu_avx_gcc_mkl:
    extends:
      - .nogpu_avx_gcc_mkl
      - .test
    needs:
      - "nogpu_avx_gcc_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_gcc_mkl:
    extends:
      - .nogpu_noavx_gcc_mkl
      - .test
    needs:
      - "nogpu_noavx_gcc_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_avx_clang_mkl:
    extends:
      - .nogpu_avx_clang_mkl
      - .test
    needs:
      - "nogpu_avx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_clang_mkl:
    extends:
      - .nogpu_noavx_clang_mkl
      - .test
    needs:
      - "nogpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

# cpu oss
nogpu_avx_gcc_oss:
    extends:
      - .nogpu_avx_gcc_oss
      - .test
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_gcc_oss:
    extends:
      - .nogpu_noavx_gcc_oss
      - .test
    needs:
      - "nogpu_noavx_gcc_oss_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_avx_clang_oss:
    extends:
      - .nogpu_avx_clang_oss
      - .test
    needs:
      - "nogpu_avx_clang_oss_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_clang_oss:
    extends:
      - .nogpu_noavx_clang_oss
      - .test
    needs:
      - "nogpu_noavx_clang_oss_build_cmake"
    script:
      - make -C test/ run_cpu

#
# Test Python module
#
pytest:
    needs: []
    stage: python
    image: ${MKL_IMAGE}
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make test_logger
python-cpu:
    artifacts:
      paths:
        - test/logger/logging
      expire_in: 360min
      when: always
    needs:
      - nogpu_avx_gcc_mkl
    image: ${MKL_IMAGE}
    stage: python
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make log_cpu
python-gpu:
    artifacts:
      paths:
        - test/logger/logging
      expire_in: 360min
      when: always
    needs:
      - gpu_avx_clang_mkl
    image: ${MKL_IMAGE}
    stage: python
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make log_gpu

#
# benchmark
#

# intel cpu + intel gpu + mkl
gpu_avx_clang_mkl_benchmark:
    stage: benchmark
    extends:
      - .gpu_avx_clang_mkl
    needs:
      - "gpu_avx_clang_mkl_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_nvidia
      - make nvidia
      - make run_nvidia
    tags:
      - c8cbb8c6304d
    only:
      - schedules
      - tags

# intel cpu + mkl
intel_avx_gcc_mkl_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_mkl
    needs:
      - "nogpu_avx_gcc_mkl_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_intel_mkl
      - make intel_mkl
      - make run_intel_mkl
    tags:
      - 008cfa52494d
    only:
      - schedules
      - tags

# intel cpu + oss
intel_avx_gcc_oss_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_oss
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_intel_oss
      - make intel_oss
      - make run_intel_oss
    tags:
      - 008cfa52494d
    only:
      - schedules
      - tags

# AMD cpu + oss
amd_avx_gcc_mkl_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_oss
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_amd_oss
      - make amd_oss
      - make run_amd_oss
    tags:
      - b42e99ecbde2
    only:
      - schedules
      - tags

benchmark_result:
    stage: deploy
    image: ${MKL_IMAGE}
    script:
        - git config --global user.name "monolish_ci_runner"
        - git config --global user.email "monolish_ci_runner@example.jp"
        - cd benchmark
        - make get_ci_info
        - make commit_result
    only:
      - schedules
      - tags

monolish_docker:
    stage: deploy
    image: docker:latest
    script:
        - cd docker; make push -j
    only:
      - master

clang_format:
    image: ghcr.io/ricosjp/allgebra/clang-format:21.05.0
    stage: build_lib
    script:
        - check_format.sh
    allow_failure: true

keep-changelog:
    image: ghcr.io/ricosjp/allgebra/clang-format:21.05.0
    stage: build_lib
    script:
        - bash -c "! git diff --exit-code origin/master CHANGELOG.md"
    allow_failure: true
    except:
        - master
        - tags
