image: alpine:latest

stages:
    - deploy

pages:
    stage: deploy
    before_script:
        - apk add doxygen
    script:
        - cd doc; doxygen; ls; cd ..
        - rm -rf public/doxygen
        - pwd; ls
        - ls doc/
        - cp -r doc/html public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
