variables:
  MKL_IMAGE: ghcr.io/ricosjp/allgebra/cuda11_4/clang12/mkl:21.09.0
  OSS_IMAGE: ghcr.io/ricosjp/allgebra/cuda11_4/clang12/oss:21.09.0
  POETRY_IMAGE: ghcr.io/ricosjp/allgebra/poetry:21.09.0

before_script:
    - export MONOLISH_DIR="${CI_PROJECT_DIR}/${PREFIX}"
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib:/usr/local/lib/

stages:
    - build_lib
    - test
    - python
    - examples
    - benchmark
    - deploy

include:
  - local: ci/env.yml
  - local: ci/build.yml
  - local: ci/test.yml
  - local: ci/python.yml
  - local: ci/example.yml
  - local: ci/benchmark.yml
  - local: ci/dev.yml
  - local: ci/docker.yml
