image: registry.ritc.jp/ricos/allgebra/cuda10_2:0.2.0

before_script:
    - export MONOLISH_DIR=${CI_PROJECT_DIR}/install_lib
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib

stages:
    - build_lib
    - test_build
    - common
    - blas
    - equation
    - logger
    - lang
    - deploy

clang_format:
    image: registry.ritc.jp/ricos/allgebra/clang-format:0.2.0
    stage: build_lib
    script:
        - check-format.sh
    allow_failure: true

## build monolish ###############################
build_cmake:
    stage: build_lib
    script:
        - cmake -Bbuild -H. -DBUILD_GPU=ON -DCMAKE_INSTALL_PREFIX=./install_lib
        - cmake --build build --target install -- -j VERBOSE=1
    artifacts:
        paths:
            - install_lib/
        expire_in: 60min
    tags:
        - gpu

## build test codes ###############################
build_test_cpu:
    stage: test_build
    script:
        - cd test/; make cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min

build_test_gpu:
    stage: test_build
    script:
        - cd test/; make gpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

## test common ###################################################

vector_common_cpu:
    stage: common
    script:
        - cd test/vector_common/
        - make run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - avx

vector_common_gpu:
    stage: common
    script:
        - cd test/vector_common/
        - make run_gpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

matrix_common_cpu:
    stage: common
    script:
        - cd test/matrix_common/
        - make run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - avx

matrix_common_gpu:
    stage: common
    script:
        - cd test/matrix_common/
        - make run_gpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu


## test blas ###################################################

vector_blas_cpu:
    stage: blas
    script:
        - cd test/vector_blas/
        - make run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - avx

vector_blas_gpu:
    stage: blas
    script:
        - cd test/vector_blas/
        - make run_gpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

matrix_blas_cpu:
    stage: blas
    script:
        - cd test/matrix_blas/
        - make run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - avx

matrix_blas_gpu:
    stage: blas
    script:
        - cd test/matrix_blas/
        - make run_gpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

## test equation ###################################################

equation_cpu:
    stage: equation
    script:
        - cd test/equation/
        - make run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - avx

equation_gpu:
    stage: equation
    script:
        - cd test/equation/
        - make run_gpu
        - make run_gpu PROFILER="nsys nvprof"
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

## test logger ###################################################

logger_cpu:
    stage: logger
    script:
        - cd test/logger/
        - make run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - avx

logger_gpu:
    stage: logger
    script:
        - cd test/logger/
        - make run_gpu
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

## test lang ###################################################

lang_cpu:
    stage: lang
    script:
        - cd test/lang/
        - make run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min

lang_gpu:
    stage: lang
    script:
        - cd test/lang/
        - make run_gpu
        - make run_gpu PROFILER="nsys nvprof"
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

## docker and pages #################################################################

docker:
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    script:
        - apk add make
        - make -C docker push
    tags:
        - docker

pages:
    image: registry.ritc.jp/ricos/allgebra/doxygen:0.2.0
    stage: deploy
    script:
        - rm -rf public html
        - doxygen Doxyfile
        - mv html public
        - cp -r test/logger/logging/*.html public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
