stages:
  - develop
  - build
  - test
  - example
  - benchmark
  - python
  - deploy

include:
  - local: ci/env.yml
  - local: ci/build.yml
  - local: ci/test.yml
  - local: ci/python.yml
  - local: ci/example.yml
  - local: ci/benchmark.yml
  - local: ci/docker.yml
  - local: ci/develop.yml
