image: registry.ritc.jp/ricos/allgebra

before_script:
    - export ENV MONOLISH_DIR=${CI_PROJECT_DIR}/install_lib
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib

stages:
    - build_lib
    - test_build
    - test
    - deploy
      
build_cpu:
    stage: build_lib
    script:
        - make cpu; make install
    artifacts:
        paths:
            - /lib/monolish/
        expire_in: 60min

build_gpu:
    stage: build_lib
    script:
        - make gpu; make install
    artifacts:
        paths:
            - /lib/monolish/
        expire_in: 60min
    tags:
        - gpu

build_test_cpu:
    stage: test_build
    script:
        - cd test/
        - make cpu
        - ls blas/dot/
    artifacts:
        paths:
            - test/
        expire_in: 60min

build_test_gpu:
    stage: test_build
    script:
        - cd test/
        - make gpu
        - ls blas/dot/
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

#####################################################
#####################################################

dot_cpu:
    stage: test
    script:
        - cd test/
        - test run_cpu
    artifacts:
        paths:
            - test/
        expire_in: 60min

dot_gpu:
    stage: test
    script:
        - cd test/
        - test run_gpu
        - test run_gpu_profile
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

pages:
    stage: deploy
    script:
        - apt update
        - apt install -y doxygen graphviz
        - cd doc; doxygen; ls; cd ..
        - rm -rf public/doxygen
        - cp -r doc/html public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
