variables:
  MKL_IMAGE: ghcr.io/ricosjp/allgebra/cuda11_4/clang12/mkl:21.09.0
  OSS_IMAGE: ghcr.io/ricosjp/allgebra/cuda11_4/clang12/oss:21.09.0
  POETRY_IMAGE: ghcr.io/ricosjp/allgebra/poetry:21.09.0

before_script:
    - export MONOLISH_DIR="${CI_PROJECT_DIR}/${PREFIX}"
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib:/usr/local/lib/

stages:
    - build_lib
    - test
    - python
    - examples
    - benchmark
    - deploy

include:
  - local: ci/build.yml

#
# Test Stage
#
.test:
  stage: test
  artifacts:
    paths:
      - test/logger/logging
    expire_in: 360min
    when: always

# gpu mkl
gpu_avx_clang_mkl:
    extends:
      - .gpu_avx_clang_mkl
      - .test
    needs:
      - "gpu_avx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_gpu

gpu_noavx_clang_mkl:
    extends:
      - .gpu_noavx_clang_mkl
      - .test
    needs:
      - "gpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_gpu

# cpu mkl
nogpu_avx_gcc_mkl:
    extends:
      - .nogpu_avx_gcc_mkl
      - .test
    needs:
      - "nogpu_avx_gcc_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_gcc_mkl:
    extends:
      - .nogpu_noavx_gcc_mkl
      - .test
    needs:
      - "nogpu_noavx_gcc_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_avx_clang_mkl:
    extends:
      - .nogpu_avx_clang_mkl
      - .test
    needs:
      - "nogpu_avx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_clang_mkl:
    extends:
      - .nogpu_noavx_clang_mkl
      - .test
    needs:
      - "nogpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C test/ run_cpu

# cpu oss
nogpu_avx_gcc_oss:
    extends:
      - .nogpu_avx_gcc_oss
      - .test
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_gcc_oss:
    extends:
      - .nogpu_noavx_gcc_oss
      - .test
    needs:
      - "nogpu_noavx_gcc_oss_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_avx_clang_oss:
    extends:
      - .nogpu_avx_clang_oss
      - .test
    needs:
      - "nogpu_avx_clang_oss_build_cmake"
    script:
      - make -C test/ run_cpu

nogpu_noavx_clang_oss:
    extends:
      - .nogpu_noavx_clang_oss
      - .test
    needs:
      - "nogpu_noavx_clang_oss_build_cmake"
    script:
      - make -C test/ run_cpu

#
# Test Python module
#
pytest:
    needs: []
    stage: python
    image: ${POETRY_IMAGE}
    script:
      - cd python
      - poetry install
      - make test_logger

.logging_artifact:
    artifacts:
      paths:
        - test/logger/logging
      expire_in: 360min
      when: always

python-cpu:
    image: ${POETRY_IMAGE}
    stage: python
    extends:
      - .logging_artifact
    needs:
      - nogpu_avx_gcc_mkl
    script:
      - cd python
      - poetry install
      - make log_cpu

python-gpu:
    image: ${POETRY_IMAGE}
    stage: python
    extends:
      - .logging_artifact
    needs:
      - gpu_avx_clang_mkl
    script:
      - cd python
      - poetry install
      - make log_gpu

#
# examples Stage
#
.examples:
  stage: examples

# gpu mkl
gpu_avx_clang_mkl_examples:
    extends:
      - .gpu_avx_clang_mkl
      - .examples
    needs:
      - "gpu_avx_clang_mkl_build_cmake"
    script:
      - make -C examples/ gpu

gpu_noavx_clang_mkl_examples:
    extends:
      - .gpu_noavx_clang_mkl
      - .examples
    needs:
      - "gpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C examples/ gpu

# cpu mkl
nogpu_avx_gcc_mkl_examples:
    extends:
      - .nogpu_avx_gcc_mkl
      - .examples
    needs:
      - "nogpu_avx_gcc_mkl_build_cmake"
    script:
      - make -C examples/ cpu

nogpu_noavx_gcc_mkl_examples:
    extends:
      - .nogpu_noavx_gcc_mkl
      - .examples
    needs:
      - "nogpu_noavx_gcc_mkl_build_cmake"
    script:
      - make -C examples/ cpu

nogpu_avx_clang_mkl_examples:
    extends:
      - .nogpu_avx_clang_mkl
      - .examples
    needs:
      - "nogpu_avx_clang_mkl_build_cmake"
    script:
      - make -C examples/ cpu

nogpu_noavx_clang_mkl_examples:
    extends:
      - .nogpu_noavx_clang_mkl
      - .examples
    needs:
      - "nogpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C examples/ cpu

# cpu oss
nogpu_avx_gcc_oss_examples:
    extends:
      - .nogpu_avx_gcc_oss
      - .examples
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    script:
      - make -C examples/ cpu

nogpu_noavx_gcc_oss_examples:
    extends:
      - .nogpu_noavx_gcc_oss
      - .examples
    needs:
      - "nogpu_noavx_gcc_oss_build_cmake"
    script:
      - make -C examples/ cpu

nogpu_avx_clang_oss_examples:
    extends:
      - .nogpu_avx_clang_oss
      - .examples
    needs:
      - "nogpu_avx_clang_oss_build_cmake"
    script:
      - make -C examples/ cpu

nogpu_noavx_clang_oss_examples:
    extends:
      - .nogpu_noavx_clang_oss
      - .examples
    needs:
      - "nogpu_noavx_clang_oss_build_cmake"
    script:
      - make -C examples/ cpu

#
# benchmark
#

# intel cpu + intel gpu + mkl
gpu_avx_clang_mkl_benchmark:
    stage: benchmark
    extends:
      - .gpu_avx_clang_mkl
    needs:
      - "gpu_avx_clang_mkl_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_nvidia
      - make nvidia
      - make run_nvidia
    tags:
      - c8cbb8c6304d
    only:
      - schedules
      - tags

# intel cpu + mkl
intel_avx_gcc_mkl_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_mkl
    needs:
      - "nogpu_avx_gcc_mkl_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_intel_mkl
      - make intel_mkl
      - make run_intel_mkl
    tags:
      - 008cfa52494d
    only:
      - schedules
      - tags

# intel cpu + oss
intel_avx_gcc_oss_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_oss
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_intel_oss
      - make intel_oss
      - make run_intel_oss
    tags:
      - 008cfa52494d
    only:
      - schedules
      - tags

# AMD cpu + oss
amd_avx_gcc_mkl_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_oss
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_amd_oss
      - make amd_oss
      - make run_amd_oss
    tags:
      - b42e99ecbde2
    only:
      - schedules
      - tags

benchmark_result:
    stage: deploy
    image: ${MKL_IMAGE}
    script:
        - git config --global user.name "monolish_ci_runner"
        - git config --global user.email "monolish_ci_runner@example.jp"
        - cd benchmark
        - make get_ci_info
        - make commit_result
    only:
      - schedules
      - tags

monolish_docker:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    script:
        - apk add coreutils make
        - cd docker; make push 
    only:
      - tags

clang_format:
    image: ghcr.io/ricosjp/allgebra/clang-format:21.06.1
    stage: build_lib
    script:
        - check_format.sh
    allow_failure: true

keep-changelog:
    image: ghcr.io/ricosjp/allgebra/clang-format:21.06.1
    stage: build_lib
    script:
        - bash -c "! git diff --exit-code origin/master... CHANGELOG.md"
    allow_failure: true
    except:
        - master
        - tags

markdown-link-check:
    image: node:16
    stage: build_lib
    script:
        - npm install -g markdown-link-check
        - markdown-link-check README.md
    allow_failure: true
