image: ghcr.io/ricosjp/allgebra/clang11gcc7/cuda10_1/mkl:latest

before_script:
    - export MONOLISH_DIR="${CI_PROJECT_DIR}/${PREFIX}"
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib

stages:
    - build_lib
    - test_build
    - vector
    - matrix
    - equation
    - logger
    - lang
    - python
    - benchmark
    - deploy

.gpu_avx_clang:
    variables:
        PREFIX: "gpu_avx"
        TEST_TARGET: "gpu"
        MONOLISH_USE_GPU: "ON"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    tags:
        - gpu
        - gpu2.gitlab-runner.savanna.ritc.jp
        - avx

.gpu_noavx_clang:
    variables:
        PREFIX: "gpu_noavx"
        TEST_TARGET: "gpu"
        MONOLISH_USE_GPU: "ON"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    tags:
        - gpu
        - gpu2.gitlab-runner.savanna.ritc.jp

.nogpu_avx_clang:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    tags:
        - avx

.nogpu_noavx_clang:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"

.nogpu_avx_gcc:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    tags:
        - avx

.nogpu_noavx_gcc:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"


.build_cmake:
    stage: build_lib
    script:
        - cmake -Bbuild . -DMONOLISH_USE_GPU=${MONOLISH_USE_GPU} -DMONOLISH_USE_AVX=${MONOLISH_USE_AVX} -DCMAKE_INSTALL_PREFIX=${MONOLISH_DIR}
        - cmake --build build --target install -- -j $(nproc) VERBOSE=1
        - make -C test -j $(nproc) ${TEST_TARGET}
    artifacts:
        paths:
            - ${PREFIX}
            - test/
        expire_in: 360min
build_cmake_gpu_avx_clang:
    extends:
      - .gpu_avx_clang
      - .build_cmake
build_cmake_gpu_noavx_clang:
    extends:
      - .gpu_noavx_clang
      - .build_cmake
build_cmake_nogpu_avx_clang:
    extends:
      - .nogpu_avx_clang
      - .build_cmake
build_cmake_nogpu_noavx_clang:
    extends:
      - .nogpu_noavx_clang
      - .build_cmake
build_cmake_nogpu_avx_gcc:
    extends:
      - .nogpu_avx_gcc
      - .build_cmake
build_cmake_nogpu_noavx_gcc:
    extends:
      - .nogpu_noavx_gcc
      - .build_cmake

#
# Test templates
#
.test_nogpu_avx_gcc:
    extends:
      - .nogpu_avx_gcc
    needs:
      - "build_cmake_nogpu_avx_gcc"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_noavx_gcc:
    extends:
      - .nogpu_noavx_gcc
    needs:
      - "build_cmake_nogpu_noavx_gcc"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_avx_clang:
    extends:
      - .nogpu_avx_clang
    needs:
      - "build_cmake_nogpu_avx_clang"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_noavx_clang:
    extends:
      - .nogpu_noavx_clang
    needs:
      - "build_cmake_nogpu_noavx_clang"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_gpu_avx_clang:
    extends:
      - .gpu_avx_clang
    needs:
      - "build_cmake_gpu_avx_clang"
    script:
      - make -C test/${TEST_TARGET} run_gpu
.test_gpu_noavx_clang:
    extends:
      - .gpu_noavx_clang
    needs:
      - "build_cmake_gpu_noavx_clang"
    script:
      - make -C test/${TEST_TARGET} run_gpu

#
# vector
#
vector_nogpu_avx_gcc:
    stage: vector
    extends: .test_nogpu_avx_gcc
    variables:
      TEST_TARGET: "vector"
vector_nogpu_noavx_gcc:
    stage: vector
    extends: .test_nogpu_noavx_gcc
    variables:
      TEST_TARGET: "vector"
vector_nogpu_avx_clang:
    stage: vector
    extends: .test_nogpu_avx_clang
    variables:
      TEST_TARGET: "vector"
vector_nogpu_noavx_clang:
    stage: vector
    extends: .test_nogpu_noavx_clang
    variables:
      TEST_TARGET: "vector"
vector_gpu_avx_clang:
    stage: vector
    extends: .test_gpu_avx_clang
    variables:
      TEST_TARGET: "vector"
vector_gpu_noavx_clang:
    stage: vector
    extends: .test_gpu_noavx_clang
    variables:
      TEST_TARGET: "vector"

#
# matrix
#
matrix_nogpu_avx_gcc:
    stage: matrix
    extends: .test_nogpu_avx_gcc
    variables:
      TEST_TARGET: "matrix"
matrix_nogpu_noavx_gcc:
    stage: matrix
    extends: .test_nogpu_noavx_gcc
    variables:
      TEST_TARGET: "matrix"
matrix_nogpu_avx_clang:
    stage: matrix
    extends: .test_nogpu_avx_clang
    variables:
      TEST_TARGET: "matrix"
matrix_nogpu_noavx_clang:
    stage: matrix
    extends: .test_nogpu_noavx_clang
    variables:
      TEST_TARGET: "matrix"
matrix_gpu_avx_clang:
    stage: matrix
    extends: .test_gpu_avx_clang
    variables:
      TEST_TARGET: "matrix"
matrix_gpu_noavx_clang:
    stage: matrix
    extends: .test_gpu_noavx_clang
    variables:
      TEST_TARGET: "matrix"

#
# equation
#
equation_nogpu_avx_gcc:
    stage: equation
    extends: .test_nogpu_avx_gcc
    variables:
      TEST_TARGET: "equation"
equation_nogpu_noavx_gcc:
    stage: equation
    extends: .test_nogpu_noavx_gcc
    variables:
      TEST_TARGET: "equation"
equation_nogpu_avx_clang:
    stage: equation
    extends: .test_nogpu_avx_clang
    variables:
      TEST_TARGET: "equation"
equation_nogpu_noavx_clang:
    stage: equation
    extends: .test_nogpu_noavx_clang
    variables:
      TEST_TARGET: "equation"
equation_gpu_avx_clang:
    stage: equation
    extends: .test_gpu_avx_clang
    variables:
      TEST_TARGET: "equation"
equation_gpu_noavx_clang:
    stage: equation
    extends: .test_gpu_noavx_clang
    variables:
      TEST_TARGET: "equation"

#
# logger
#
.logger_artifact:
    artifacts:
      paths:
        - test/logger/logging
      expire_in: 360min
      when: always
logger_nogpu_avx_gcc:
    stage: logger
    extends:
      - .test_nogpu_avx_gcc
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
logger_nogpu_noavx_gcc:
    stage: logger
    extends:
      - .test_nogpu_noavx_gcc
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
logger_nogpu_avx_clang:
    stage: logger
    extends:
      - .test_nogpu_avx_clang
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
logger_nogpu_noavx_clang:
    stage: logger
    extends:
      - .test_nogpu_noavx_clang
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
logger_gpu_avx_clang:
    stage: logger
    extends:
      - .test_gpu_avx_clang
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
logger_gpu_noavx_clang:
    stage: logger
    extends:
      - .test_gpu_noavx_clang
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"

#
# lang
#
lang_nogpu_avx_gcc:
    stage: lang
    extends: .test_nogpu_avx_gcc
    variables:
      TEST_TARGET: "lang"
lang_nogpu_noavx_gcc:
    stage: lang
    extends: .test_nogpu_noavx_gcc
    variables:
      TEST_TARGET: "lang"
lang_nogpu_avx_clang:
    stage: lang
    extends: .test_nogpu_avx_clang
    variables:
      TEST_TARGET: "lang"
lang_nogpu_noavx_clang:
    stage: lang
    extends: .test_nogpu_noavx_clang
    variables:
      TEST_TARGET: "lang"
lang_gpu_avx_clang:
    stage: lang
    extends: .test_gpu_avx_clang
    variables:
      TEST_TARGET: "lang"
lang_gpu_noavx_clang:
    stage: lang
    extends: .test_gpu_noavx_clang
    variables:
      TEST_TARGET: "lang"

#
# Test Python module
#
pytest:
    needs: []
    stage: python
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make test_logger
python-cpu:
    extends:
      - .logger_artifact
    needs:
      - logger_nogpu_avx_gcc
    stage: python
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make log_cpu
python-gpu:
    extends:
      - .logger_artifact
    needs:
      - logger_gpu_avx_clang
    stage: python
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make log_gpu

#
# benchmark
#
benchmark_nogpu_avx_gcc:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc
    needs:
      - "build_cmake_nogpu_avx_gcc"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_cpu
      - make cpu
      - make run_cpu
    tags:
      - cpu2.gitlab-runner.savanna.ritc.jp
    only:
        - master
        - 394-clang11gcc7-benchmark-size
    except:
        - schedules
        - tags

benchmark_gpu_avx_clang:
    stage: benchmark
    extends:
      - .gpu_avx_clang
    needs:
      - "build_cmake_gpu_avx_clang"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_gpu
      - make gpu
      - make run_gpu
    tags:
      - gpu2.gitlab-runner.savanna.ritc.jp
    only:
        - master
        - 394-clang11gcc7-benchmark-size
    except:
        - schedules
        - tags

#
# docker and pages
#
docker:
    # dependencies: require all tests
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    script:
        - apk add make
        - make -C docker push
    tags:
        - docker

pages:
    dependencies:
      - python-cpu
      - python-gpu
    image: ghcr.io/ricosjp/allgebra/doxygen:20.10.1
    stage: deploy
    script:
        - rm -rf public html
        - doxygen Doxyfile
        - mv html public
        - cp -r test/logger/logging/*.html public/
    artifacts:
        paths:
            - public
        expire_in: 360min
    only:
        - master

benchmark_result:
    stage: deploy
    script:
        - git config --global user.name "monolish_ci_runner"
        - git config --global user.email "monolish_ci_runner@example.jp"
        - cd benchmark
        - make get_ci_info
        - make commit_result
    only:
        - master
        - 394-clang11gcc7-benchmark-size
    except:
        - schedules
        - tags

clang_format:
    image: ghcr.io/ricosjp/allgebra/clang-format:20.10.1
    stage: build_lib
    script:
        - check-format.sh
    allow_failure: true

keep-changelog:
    image: ghcr.io/ricosjp/allgebra/clang-format:20.10.1
    stage: build_lib
    script:
        - bash -c "! git diff --exit-code origin/master CHANGELOG.md"
    allow_failure: true
    except:
        - master
        - tags
