variables:
  MKL_IMAGE: ghcr.io/ricosjp/allgebra/cuda11_4/clang12/mkl:21.09.0
  OSS_IMAGE: ghcr.io/ricosjp/allgebra/cuda11_4/clang12/oss:21.09.0
  POETRY_IMAGE: ghcr.io/ricosjp/allgebra/poetry:21.09.0

before_script:
    - export MONOLISH_DIR="${CI_PROJECT_DIR}/${PREFIX}"
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib:/usr/local/lib/

stages:
    - build_lib
    - test
    - python
    - examples
    - benchmark
    - deploy

include:
  - local: ci/env.yml
  - local: ci/build.yml
  - local: ci/test.yml
  - local: ci/python.yml
  - local: ci/example.yml
  - local: ci/benchmark.yml

monolish_docker:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    script:
        - apk add coreutils make
        - cd docker; make push 
    only:
      - tags

clang_format:
    image: ghcr.io/ricosjp/allgebra/clang-format:21.06.1
    stage: build_lib
    script:
        - check_format.sh
    allow_failure: true

keep-changelog:
    image: ghcr.io/ricosjp/allgebra/clang-format:21.06.1
    stage: build_lib
    script:
        - bash -c "! git diff --exit-code origin/master... CHANGELOG.md"
    allow_failure: true
    except:
        - master
        - tags

markdown-link-check:
    image: node:16
    stage: build_lib
    script:
        - npm install -g markdown-link-check
        - markdown-link-check README.md
    allow_failure: true
