image: registry.ritc.jp/ricos/allgebra/base

before_script:
    - export MONOLISH_DIR=${CI_PROJECT_DIR}/install_lib
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib

stages:
    - build_lib
    - test_build
    - common
    - blas_lv1
    - sparse
    - solver
    - deploy
      
build_cpu:
    stage: build_lib
    script:
        - make cpu; make install
    artifacts:
        paths:
            - install_lib/
        expire_in: 60min

build_gpu:
    stage: build_lib
    script:
        - make gpu; make install
    artifacts:
        paths:
            - install_lib/
        expire_in: 60min
    tags:
        - gpu

build_test_cpu:
    stage: test_build
    script:
        - cd test/
        - make cpu
        - ls blas/dot/
    artifacts:
        paths:
            - test/
        expire_in: 60min

build_test_gpu:
    stage: test_build
    script:
        - cd test/
        - make gpu
        - ls blas/dot/
    artifacts:
        paths:
            - test/
        expire_in: 60min
    tags:
        - gpu

#####################################################
#####################################################

include:
    - '.git-ci/common.yml'
    - '.git-ci/blas1.yml'
    - '.git-ci/spmv.yml'
    - '.git-ci/solver.yml'

#####################################################
#####################################################

docker:
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    script:
        - apk add make
        - cp -r install_lib/lib/ docker/
        - cp -r install_lib/include/ docker/
        - ls docker/
        - cd docker; make push; cd ..
    tags:
        - docker

pages:
    stage: deploy
    script:
        - apt update
        - apt install -y doxygen graphviz
        - cd doc; doxygen; ls; cd ..
        - rm -rf public/doxygen
        - cp -r doc/html public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
        - 32-doxygen-install-guide
