image: alpine:latest

stages:
    - build
    - deploy

document:
    stage: build
    before_script:
        - apk add doxygen
    script:
        - cd doc; doxygen; ls; cd ..
        - rm -rf public/doxygen
        - mv doc/html/ public/doxygen
    artifacts:
        paths:
            - public
        expire_in: 100min
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    only:
        - master

pages:
    stage: deploy
    dependencies:
        - document
    script:
        - ls public
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
