variables:
  MKL_IMAGE: ghcr.io/ricosjp/allgebra/cuda10_1/clang11gcc7/mkl:20.12.1
  OSS_IMAGE: ghcr.io/ricosjp/allgebra/cuda10_1/clang11gcc7/oss:20.12.1


before_script:
    - export MONOLISH_DIR="${CI_PROJECT_DIR}/${PREFIX}"
    - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib

stages:
    - build_lib
    - test_build
    - vector
    - matrix
    - equation
    - logger
    - lang
    - python
    - benchmark
    - deploy

# gpu mkl
.gpu_avx_clang_mkl:
    variables:
        PREFIX: "gpu_avx"
        TEST_TARGET: "gpu"
        MONOLISH_USE_GPU: "ON"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    tags:
        - gpu
        - nvidia0-sm_61
        - avx
    image: ${MKL_IMAGE}

.gpu_noavx_clang_mkl:
    variables:
        PREFIX: "gpu_noavx"
        TEST_TARGET: "gpu"
        MONOLISH_USE_GPU: "ON"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    tags:
        - gpu
        - nvidia0-sm_61
    image: ${MKL_IMAGE}

# cpu mkl
.nogpu_avx_clang_mkl:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    tags:
        - avx
    image: ${MKL_IMAGE}

.nogpu_noavx_clang_mkl:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    image: ${MKL_IMAGE}

.nogpu_avx_gcc_mkl:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    tags:
        - avx
    image: ${MKL_IMAGE}

.nogpu_noavx_gcc_mkl:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    image: ${MKL_IMAGE}

# cpu oss
.nogpu_avx_clang_oss:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    tags:
        - avx
    image: ${OSS_IMAGE}

.nogpu_noavx_clang_oss:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/local/llvm-11.0.0/bin/clang"
        CXX: "/usr/local/llvm-11.0.0/bin/clang++"
    image: ${OSS_IMAGE}

.nogpu_avx_gcc_oss:
    variables:
        PREFIX: "nogpu_avx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "ON"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    tags:
        - avx
    image: ${OSS_IMAGE}

.nogpu_noavx_gcc_oss:
    variables:
        PREFIX: "nogpu_noavx"
        TEST_TARGET: "cpu"
        MONOLISH_USE_GPU: "OFF"
        MONOLISH_USE_AVX: "OFF"
        CC: "/usr/bin/gcc"
        CXX: "/usr/bin/g++"
    image: ${OSS_IMAGE}

#
# Build stage
#
.build_cmake:
    stage: build_lib
    script:
        - cmake -Bbuild . -DMONOLISH_USE_GPU=${MONOLISH_USE_GPU} -DMONOLISH_USE_AVX=${MONOLISH_USE_AVX} -DCMAKE_INSTALL_PREFIX=${MONOLISH_DIR}
        - cmake --build build --target install -- -j $(nproc) VERBOSE=1
        - make -C test -j $(nproc) ${TEST_TARGET}
    artifacts:
        paths:
            - ${PREFIX}
            - test/
        expire_in: 360min

# gpu mkl
gpu_avx_clang_mkl_build_cmake:
    extends:
      - .gpu_avx_clang_mkl
      - .build_cmake
gpu_noavx_clang_mkl_build_cmake:
    extends:
      - .gpu_noavx_clang_mkl
      - .build_cmake
# cpu mkl
nogpu_avx_clang_mkl_build_cmake:
    extends:
      - .nogpu_avx_clang_mkl
      - .build_cmake
nogpu_noavx_clang_mkl_build_cmake:
    extends:
      - .nogpu_noavx_clang_mkl
      - .build_cmake
nogpu_avx_gcc_mkl_build_cmake:
    extends:
      - .nogpu_avx_gcc_mkl
      - .build_cmake
nogpu_noavx_gcc_mkl_build_cmake:
    extends:
      - .nogpu_noavx_gcc_mkl
      - .build_cmake
# cpu oss
nogpu_avx_clang_oss_build_cmake:
    extends:
      - .nogpu_avx_clang_oss
      - .build_cmake
nogpu_noavx_clang_oss_build_cmake:
    extends:
      - .nogpu_noavx_clang_oss
      - .build_cmake
nogpu_avx_gcc_oss_build_cmake:
    extends:
      - .nogpu_avx_gcc_oss
      - .build_cmake
nogpu_noavx_gcc_oss_build_cmake:
    extends:
      - .nogpu_noavx_gcc_oss
      - .build_cmake

#
# Test templates
#

# gpu mkl
.test_gpu_avx_clang_mkl:
    extends:
      - .gpu_avx_clang_mkl
    needs:
      - "gpu_avx_clang_mkl_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_gpu
.test_gpu_noavx_clang_mkl:
    extends:
      - .gpu_noavx_clang_mkl
    needs:
      - "gpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_gpu
## cpu mkl
.test_nogpu_avx_gcc_mkl:
    extends:
      - .nogpu_avx_gcc_mkl
    needs:
      - "nogpu_avx_gcc_mkl_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_noavx_gcc_mkl:
    extends:
      - .nogpu_noavx_gcc_mkl
    needs:
      - "nogpu_noavx_gcc_mkl_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_avx_clang_mkl:
    extends:
      - .nogpu_avx_clang_mkl
    needs:
      - "nogpu_avx_clang_mkl_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_noavx_clang_mkl:
    extends:
      - .nogpu_noavx_clang_mkl
    needs:
      - "nogpu_noavx_clang_mkl_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu
# cpu oss
.test_nogpu_avx_gcc_oss:
    extends:
      - .nogpu_avx_gcc_oss
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_noavx_gcc_oss:
    extends:
      - .nogpu_noavx_gcc_oss
    needs:
      - "nogpu_noavx_gcc_oss_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_avx_clang_oss:
    extends:
      - .nogpu_avx_clang_oss
    needs:
      - "nogpu_avx_clang_oss_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu
.test_nogpu_noavx_clang_oss:
    extends:
      - .nogpu_noavx_clang_oss
    needs:
      - "nogpu_noavx_clang_oss_build_cmake"
    script:
      - make -C test/${TEST_TARGET} run_cpu

#
# vector
#

# gpu mkl
gpu_avx_clang_mkl_vector:
    stage: vector
    extends: .test_gpu_avx_clang_mkl
    variables:
      TEST_TARGET: "vector"
gpu_noavx_clang_mkl_vector:
    stage: vector
    extends: .test_gpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "vector"
# cpu mkl
nogpu_avx_gcc_mkl_vector:
    stage: vector
    extends: .test_nogpu_avx_gcc_mkl
    variables:
      TEST_TARGET: "vector"
nogpu_noavx_gcc_mkl_vector:
    stage: vector
    extends: .test_nogpu_noavx_gcc_mkl
    variables:
      TEST_TARGET: "vector"
nogpu_avx_clang_mkl_vector:
    stage: vector
    extends: .test_nogpu_avx_clang_mkl
    variables:
      TEST_TARGET: "vector"
nogpu_noavx_clang_mkl_vector:
    stage: vector
    extends: .test_nogpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "vector"
# cpu oss
nogpu_avx_gcc_oss_vector:
    stage: vector
    extends: .test_nogpu_avx_gcc_oss
    variables:
      TEST_TARGET: "vector"
nogpu_noavx_gcc_oss_vector:
    stage: vector
    extends: .test_nogpu_noavx_gcc_oss
    variables:
      TEST_TARGET: "vector"
nogpu_avx_clang_oss_vector:
    stage: vector
    extends: .test_nogpu_avx_clang_oss
    variables:
      TEST_TARGET: "vector"
nogpu_noavx_clang_oss_vector:
    stage: vector
    extends: .test_nogpu_noavx_clang_oss
    variables:
      TEST_TARGET: "vector"

#
# matrix
#

# gpu mkl
gpu_avx_clang_mkl_matrix:
    stage: matrix
    extends: .test_gpu_avx_clang_mkl
    variables:
      TEST_TARGET: "matrix"
gpu_noavx_clang_mkl_matrix:
    stage: matrix
    extends: .test_gpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "matrix"
# cpu mkl
nogpu_avx_gcc_mkl_matrix:
    stage: matrix
    extends: .test_nogpu_avx_gcc_mkl
    variables:
      TEST_TARGET: "matrix"
nogpu_noavx_gcc_mkl_matrix:
    stage: matrix
    extends: .test_nogpu_noavx_gcc_mkl
    variables:
      TEST_TARGET: "matrix"
nogpu_avx_clang_mkl_matrix:
    stage: matrix
    extends: .test_nogpu_avx_clang_mkl
    variables:
      TEST_TARGET: "matrix"
nogpu_noavx_clang_mkl_matrix:
    stage: matrix
    extends: .test_nogpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "matrix"
# cpu oss
nogpu_avx_gcc_oss_matrix:
    stage: matrix
    extends: .test_nogpu_avx_gcc_oss
    variables:
      TEST_TARGET: "matrix"
nogpu_noavx_gcc_oss_matrix:
    stage: matrix
    extends: .test_nogpu_noavx_gcc_oss
    variables:
      TEST_TARGET: "matrix"
nogpu_avx_clang_oss_matrix:
    stage: matrix
    extends: .test_nogpu_avx_clang_oss
    variables:
      TEST_TARGET: "matrix"
nogpu_noavx_clang_oss_matrix:
    stage: matrix
    extends: .test_nogpu_noavx_clang_oss
    variables:
      TEST_TARGET: "matrix"

#
# equation
#

# gpu mkl
gpu_avx_clang_mkl_equation:
    stage: equation
    extends: .test_gpu_avx_clang_mkl
    variables:
      TEST_TARGET: "equation"
gpu_noavx_clang_mkl_equation:
    stage: equation
    extends: .test_gpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "equation"
# cpu mkl
nogpu_avx_gcc_mkl_equation:
    stage: equation
    extends: .test_nogpu_avx_gcc_mkl
    variables:
      TEST_TARGET: "equation"
nogpu_noavx_gcc_mkl_equation:
    stage: equation
    extends: .test_nogpu_noavx_gcc_mkl
    variables:
      TEST_TARGET: "equation"
nogpu_avx_clang_mkl_equation:
    stage: equation
    extends: .test_nogpu_avx_clang_mkl
    variables:
      TEST_TARGET: "equation"
nogpu_noavx_clang_mkl_equation:
    stage: equation
    extends: .test_nogpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "equation"
# cpu oss
nogpu_avx_gcc_oss_equation:
    stage: equation
    extends: .test_nogpu_avx_gcc_oss
    variables:
      TEST_TARGET: "equation"
nogpu_noavx_gcc_oss_equation:
    stage: equation
    extends: .test_nogpu_noavx_gcc_oss
    variables:
      TEST_TARGET: "equation"
nogpu_avx_clang_oss_equation:
    stage: equation
    extends: .test_nogpu_avx_clang_oss
    variables:
      TEST_TARGET: "equation"
nogpu_noavx_clang_oss_equation:
    stage: equation
    extends: .test_nogpu_noavx_clang_oss
    variables:
      TEST_TARGET: "equation"

#
# logger
#
.logger_artifact:
  artifacts:
    paths:
      - test/logger/logging
    expire_in: 360min
    when: always
# gpu mkl
gpu_avx_clang_mkl_logger:
    stage: logger
    extends: 
      - .test_gpu_avx_clang_mkl
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
gpu_noavx_clang_mkl_logger:
    stage: logger
    extends: 
      - .test_gpu_noavx_clang_mkl
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
# cpu mkl
nogpu_avx_gcc_mkl_logger:
    stage: logger
    extends:
      - .test_nogpu_avx_gcc_mkl
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
nogpu_noavx_gcc_mkl_logger:
    stage: logger
    extends:
      - .test_nogpu_noavx_gcc_mkl
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
nogpu_avx_clang_mkl_logger:
    stage: logger
    extends:
      - .test_nogpu_avx_clang_mkl
      - .logger_artifact
    variables:
     TEST_TARGET: "logger"
nogpu_noavx_clang_mkl_logger:
    stage: logger
    extends:
      - .test_nogpu_noavx_clang_mkl
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
# cpu oss
nogpu_avx_gcc_oss_logger:
    stage: logger
    extends:
      - .test_nogpu_avx_gcc_oss
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
nogpu_noavx_gcc_oss_logger:
    stage: logger
    extends:
      - .test_nogpu_noavx_gcc_oss
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
nogpu_avx_clang_oss_logger:
    stage: logger
    extends:
      - .test_nogpu_avx_clang_oss
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"
nogpu_noavx_clang_oss_logger:
    stage: logger
    extends:
      - .test_nogpu_noavx_clang_oss
      - .logger_artifact
    variables:
      TEST_TARGET: "logger"

#
# lang
#

# gpu mkl
gpu_avx_clang_mkl_lang:
    stage: lang
    extends: .test_gpu_avx_clang_mkl
    variables:
      TEST_TARGET: "lang"
gpu_noavx_clang_mkl_lang:
    stage: lang
    extends: .test_gpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "lang"
# cpu mkl
nogpu_avx_gcc_mkl_lang:
    stage: lang
    extends: .test_nogpu_avx_gcc_mkl
    variables:
      TEST_TARGET: "lang"
nogpu_noavx_gcc_mkl_lang:
    stage: lang
    extends: .test_nogpu_noavx_gcc_mkl
    variables:
      TEST_TARGET: "lang"
nogpu_avx_clang_mkl_lang:
    stage: lang
    extends: .test_nogpu_avx_clang_mkl
    variables:
      TEST_TARGET: "lang"
nogpu_noavx_clang_mkl_lang:
    stage: lang
    extends: .test_nogpu_noavx_clang_mkl
    variables:
      TEST_TARGET: "lang"
# cpu oss
nogpu_avx_gcc_oss_lang:
    stage: lang
    extends: .test_nogpu_avx_gcc_oss
    variables:
      TEST_TARGET: "lang"
nogpu_noavx_gcc_oss_lang:
    stage: lang
    extends: .test_nogpu_noavx_gcc_oss
    variables:
      TEST_TARGET: "lang"
nogpu_avx_clang_oss_lang:
    stage: lang
    extends: .test_nogpu_avx_clang_oss
    variables:
      TEST_TARGET: "lang"
nogpu_noavx_clang_oss_lang:
    stage: lang
    extends: .test_nogpu_noavx_clang_oss
    variables:
      TEST_TARGET: "lang"

#
# Test Python module
#
pytest:
    needs: []
    stage: python
    image: ${MKL_IMAGE}
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make test_logger
python-cpu:
    extends:
      - .logger_artifact
    needs:
      - nogpu_avx_gcc_mkl_logger
    image: ${MKL_IMAGE}
    stage: python
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make log_cpu
python-gpu:
    extends:
      - .logger_artifact
    needs:
      - gpu_avx_clang_mkl_logger
    image: ${MKL_IMAGE}
    stage: python
    script:
      # FIXME Python setup should be moved into allgebra
      - apt update && apt install -y python3-pip
      - python3 -m pip install poetry
      # Test monolish_log_viewer
      - cd python
      - poetry install
      - make log_gpu

#
# benchmark
#

# intel cpu + intel gpu + mkl
gpu_avx_clang_mkl_benchmark:
    stage: benchmark
    extends:
      - .gpu_avx_clang_mkl
    needs:
      - "gpu_avx_clang_mkl_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_gpu
      - make gpu
      - make run_gpu
    tags:
      - c8cbb8c6304d
    only:
      - schedules

# intel cpu + mkl
intel_avx_gcc_mkl_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_mkl
    needs:
      - "nogpu_avx_gcc_mkl_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_cpu
      - make cpu
      - make run_cpu
    tags:
      - 008cfa52494d
    only:
      - schedules

# intel cpu + oss
intel_avx_gcc_oss_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_oss
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_cpu
      - make cpu
      - make run_cpu
    tags:
      - 008cfa52494d
    only:
      - schedules

# AMD cpu + oss
amd_avx_gcc_mkl_benchmark:
    stage: benchmark
    extends:
      - .nogpu_avx_gcc_oss
    needs:
      - "nogpu_avx_gcc_oss_build_cmake"
    artifacts:
        paths:
            - benchmark/
        expire_in: 360min
    script:
      - cd benchmark
      - make get_spec_cpu
      - make cpu
      - make run_cpu
    tags:
      - b42e99ecbde2
    only:
      - schedules

#
# docker and pages
#
docker:
    # dependencies: require all tests
    image: docker:latest
    stage: deploy
    services:
        - docker:dind
    script:
        - apk add make
        - make -C docker push
    tags:
        - docker

pages:
    dependencies:
      - python-cpu
      - python-gpu
    image: ghcr.io/ricosjp/allgebra/doxygen:20.10.1
    stage: deploy
    script:
        - rm -rf public html
        - doxygen Doxyfile
        - mv html public
        - cp -r test/logger/logging/*.html public/
    artifacts:
        paths:
            - public
        expire_in: 360min
    only:
        - master

benchmark_result:
    stage: deploy
    image: ${MKL_IMAGE}
    script:
        - git config --global user.name "monolish_ci_runner"
        - git config --global user.email "monolish_ci_runner@example.jp"
        - cd benchmark
        - make get_ci_info
        - make commit_result
    only:
        - master
    except:
        - schedules
        - tags

clang_format:
    image: ghcr.io/ricosjp/allgebra/clang-format:20.10.1
    stage: build_lib
    script:
        - check-format.sh
    allow_failure: true

keep-changelog:
    image: ghcr.io/ricosjp/allgebra/clang-format:20.10.1
    stage: build_lib
    script:
        - bash -c "! git diff --exit-code origin/master CHANGELOG.md"
    allow_failure: true
    except:
        - master
        - tags
