before_script:
  - export MONOLISH_DIR="${CI_PROJECT_DIR}/${PREFIX}"
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MONOLISH_DIR}/lib:/usr/local/lib/

stages:
  - build_lib
  - test
  - example
  - benchmark
  - python
  - develop
  - deploy

include:
  - local: ci/env.yml
  - local: ci/build.yml
  - local: ci/test.yml
  - local: ci/python.yml
  - local: ci/example.yml
  - local: ci/benchmark.yml
  - local: ci/docker.yml
  - local: ci/develop.yml
