image: centos:latest

stages:
    - deploy

pages:
    stage: deploy
    before_script:
        - dnf --enablerepo=PowerTools install -y doxygen graphviz
    script:
        - cd doc; doxygen; ls; cd ..
        - rm -rf public/doxygen
        - cp -r doc/html public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
