# gpu mkl
.gpu_avx_clang_mkl:
  variables:
    PREFIX: "gpu_avx"
    TEST_TARGET: "gpu"
    MONOLISH_USE_NVIDIA_GPU: "ON"
    MONOLISH_USE_AVX: "ON"
    CC: "/usr/local/llvm-12.0.1/bin/clang"
    CXX: "/usr/local/llvm-12.0.1/bin/clang++"
  tags:
    - gpu
    - nvidia0-sm_61
    - avx
  image: ${MKL_IMAGE}

.gpu_noavx_clang_mkl:
  variables:
    PREFIX: "gpu_noavx"
    TEST_TARGET: "gpu"
    MONOLISH_USE_NVIDIA_GPU: "ON"
    MONOLISH_USE_AVX: "OFF"
    CC: "/usr/local/llvm-12.0.1/bin/clang"
    CXX: "/usr/local/llvm-12.0.1/bin/clang++"
  tags:
    - gpu
    - nvidia0-sm_61
  image: ${MKL_IMAGE}

.nogpu_avx_clang_mkl:
  variables:
    PREFIX: "nogpu_avx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "ON"
    CC: "/usr/local/llvm-12.0.1/bin/clang"
    CXX: "/usr/local/llvm-12.0.1/bin/clang++"
  tags:
    - avx
  image: ${MKL_IMAGE}

.nogpu_noavx_clang_mkl:
  variables:
    PREFIX: "nogpu_noavx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "OFF"
    CC: "/usr/local/llvm-12.0.1/bin/clang"
    CXX: "/usr/local/llvm-12.0.1/bin/clang++"
  image: ${MKL_IMAGE}

.nogpu_avx_gcc_mkl:
  variables:
    PREFIX: "nogpu_avx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "ON"
    CC: "/usr/bin/gcc"
    CXX: "/usr/bin/g++"
  tags:
    - avx
  image: ${MKL_IMAGE}

.nogpu_noavx_gcc_mkl:
  variables:
    PREFIX: "nogpu_noavx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "OFF"
    CC: "/usr/bin/gcc"
    CXX: "/usr/bin/g++"
  image: ${MKL_IMAGE}

.nogpu_avx_clang_oss:
  variables:
    PREFIX: "nogpu_avx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "ON"
    CC: "/usr/local/llvm-12.0.1/bin/clang"
    CXX: "/usr/local/llvm-12.0.1/bin/clang++"
  tags:
    - avx
  image: ${OSS_IMAGE}

.nogpu_noavx_clang_oss:
  variables:
    PREFIX: "nogpu_noavx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "OFF"
    CC: "/usr/local/llvm-12.0.1/bin/clang"
    CXX: "/usr/local/llvm-12.0.1/bin/clang++"
  image: ${OSS_IMAGE}

.nogpu_avx_gcc_oss:
  variables:
    PREFIX: "nogpu_avx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "ON"
    CC: "/usr/bin/gcc"
    CXX: "/usr/bin/g++"
  tags:
    - avx
  image: ${OSS_IMAGE}

.nogpu_noavx_gcc_oss:
  variables:
    PREFIX: "nogpu_noavx"
    TEST_TARGET: "cpu"
    MONOLISH_USE_NVIDIA_GPU: "OFF"
    MONOLISH_USE_AVX: "OFF"
    CC: "/usr/bin/gcc"
    CXX: "/usr/bin/g++"
  image: ${OSS_IMAGE}

#
# Build stage
#
.build_cmake:
  stage: build_lib
  script:
    - apt update -y; apt install -y gfortran
    - cmake -Bbuild . -DMONOLISH_USE_NVIDIA_GPU=${MONOLISH_USE_NVIDIA_GPU} -DMONOLISH_USE_AVX=${MONOLISH_USE_AVX} -DCMAKE_INSTALL_PREFIX=${MONOLISH_DIR}
    - cmake --build build --target install -- -j $(nproc) VERBOSE=1
    - make -C test -j $(nproc) ${TEST_TARGET}
  artifacts:
    paths:
      - ${PREFIX}
      - test/
    expire_in: 360min

gpu_avx_clang_mkl_build_cmake:
  extends:
    - .gpu_avx_clang_mkl
    - .build_cmake
gpu_noavx_clang_mkl_build_cmake:
  extends:
    - .gpu_noavx_clang_mkl
    - .build_cmake
nogpu_avx_clang_mkl_build_cmake:
  extends:
    - .nogpu_avx_clang_mkl
    - .build_cmake
nogpu_noavx_clang_mkl_build_cmake:
  extends:
    - .nogpu_noavx_clang_mkl
    - .build_cmake
nogpu_avx_gcc_mkl_build_cmake:
  extends:
    - .nogpu_avx_gcc_mkl
    - .build_cmake
nogpu_noavx_gcc_mkl_build_cmake:
  extends:
    - .nogpu_noavx_gcc_mkl
    - .build_cmake
nogpu_avx_clang_oss_build_cmake:
  extends:
    - .nogpu_avx_clang_oss
    - .build_cmake
nogpu_noavx_clang_oss_build_cmake:
  extends:
    - .nogpu_noavx_clang_oss
    - .build_cmake
nogpu_avx_gcc_oss_build_cmake:
  extends:
    - .nogpu_avx_gcc_oss
    - .build_cmake
nogpu_noavx_gcc_oss_build_cmake:
  extends:
    - .nogpu_noavx_gcc_oss
    - .build_cmake

# MPI_build_test:
#   stage: build_lib
#   script:
#     - nvidia-smi
#     - make install_all
#     - cd test/mpi; make clean; make -j; make run
#   image: ${MKL_IMAGE}
#   tags:
#     - 2-gpu
#     - nvidia0-sm_61
#     - avx

