#
# Build stage
#
.build:
  stage: build_lib
  script:
    - apt update
    - apt install -y gfortran
    - cmake --preset=${PRESET}
    - cmake --build build/${PRESET}
    - cd build/${PRESET}
    - rm -rf *.deb
    - cpack -G DEB
    - apt install -y ./$(find *.deb)
    - make -C test -j $(nproc) ${TEST_TARGET}
  artifacts:
    paths:
      - build/${PREFIX}
      - test/
    expire_in: 360min

gpu_avx_clang_mkl_build:
  extends:
    - .mkl_image
    - .gpu_avx_clang
    - .build
gpu_noavx_clang_mkl_build:
  extends:
    - .mkl_image
    - .gpu_noavx_clang
    - .build
cpu_avx_clang_mkl_build:
  extends:
    - .mkl_image
    - .cpu_avx_clang
    - .build
cpu_none_clang_mkl_build:
  extends:
    - .mkl_image
    - .cpu_none_clang
    - .build
cpu_avx_gcc_mkl_build:
  extends:
    - .mkl_image
    - .cpu_avx_gcc
    - .build
cpu_none_gcc_mkl_build:
  extends:
    - .mkl_image
    - .cpu_none_gcc
    - .build
cpu_avx_clang_oss_build:
  extends:
    - .oss_image
    - .cpu_avx_clang
    - .build
cpu_none_clang_oss_build:
  extends:
    - .oss_image
    - .cpu_none_clang
    - .build
cpu_avx_gcc_oss_build:
  extends:
    - .oss_image
    - .cpu_avx_gcc
    - .build
cpu_none_gcc_oss_build:
  extends:
    - .oss_image
    - .cpu_none_gcc
    - .build

# MPI_build_test:
#   stage: build_lib
#   script:
#     - nvidia-smi
#     - make install_all
#     - cd test/mpi; make clean; make -j; make run
#   image: ${MKL_IMAGE}
#   tags:
#     - 2-gpu
#     - nvidia0-sm_61
#     - avx

