#
# Build stage
#
.ccache:
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  cache:
    key: ccache
    paths:
      - ${CI_PROJECT_DIR}/ccache

.build:
  stage: build
  extends:
    - .ccache
  script:
    - apt update
    - apt install -y gfortran ccache
    - cmake --preset=${PRESET}
    - cmake --build build/${PRESET} --target package
    - mv build/${PRESET}/{*.deb,Dockerfile,compose.yml} ${CI_PROJECT_DIR}
    - apt install -y ./$(find . -name "*.deb")
    - make -C test -j $(nproc) ${TEST_TARGET}
  artifacts:
    paths:
      - "*.deb"
      - Dockerfile
      - compose.yml
      - test/
    expire_in: 1 day
  needs: []

.build_all:
  stage: build
  extends:
    - .ccache
  script:
    - apt update
    - apt install -y gfortran ccache
    - cmake --preset=${PRESET}
    - cmake --build build/${PRESET} --target package
    - mv build/${PRESET}/{*.deb,Dockerfile,compose.yml} ${CI_PROJECT_DIR}
  artifacts:
    paths:
      - "*.deb"
      - Dockerfile
      - compose.yml
    expire_in: 1 day
  needs: []
  tags:
    - cpu-ge-8
  only:
    - master
    - tags

gpu_all_mkl_build:
  extends:
    - .mkl_image
    - .gpu_all
    - .build_all
gpu_all_oss_build:
  extends:
    - .oss_image
    - .gpu_all
    - .build_all

# MPI_build_test:
#   stage: build_lib
#   script:
#     - nvidia-smi
#     - make install_all
#     - cd test/mpi; make clean; make -j; make run
#   image: ${MKL_IMAGE}
#   tags:
#     - 2-gpu
#     - nvidia0-sm_61
#     - avx

