#
# Build stage
#
.build:
  stage: build
  script:
    - apt update
    - apt install -y gfortran ccache
    - cmake --preset=${PRESET}
    - cmake --build build/${PRESET} --target package
    - mv build/${PRESET}/{*.deb,Dockerfile,compose.yml} ${CI_PROJECT_DIR}
    - apt install -y ./$(find . -name "*.deb")
    - make -C test -j $(nproc) ${TEST_TARGET}
  artifacts:
    paths:
      - "*.deb"
      - Dockerfile
      - compose.yml
      - test/
    expire_in: 360min
  needs: []
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  cache:
    key: ccache
    paths:
      - ${CI_PROJECT_DIR}/ccache

gpu_avx_mkl_build:
  extends:
    - .mkl_image
    - .gpu_avx
    - .build
gpu_none_mkl_build:
  extends:
    - .mkl_image
    - .gpu_none
    - .build
gpu_avx_oss_build:
  extends:
    - .oss_image
    - .gpu_avx
    - .build
gpu_none_oss_build:
  extends:
    - .oss_image
    - .gpu_none
    - .build
gpu_all_mkl_build:
  extends:
    - .mkl_image
    - .gpu_all
    - .build
gpu_all_oss_build:
  extends:
    - .oss_image
    - .gpu_all
    - .build
cpu_avx_mkl_build:
  extends:
    - .mkl_image
    - .cpu_avx
    - .build
cpu_none_mkl_build:
  extends:
    - .mkl_image
    - .cpu_none
    - .build
cpu_avx_gcc_mkl_build:
  extends:
    - .mkl_image
    - .cpu_avx_gcc
    - .build
cpu_none_gcc_mkl_build:
  extends:
    - .mkl_image
    - .cpu_none_gcc
    - .build
cpu_avx_oss_build:
  extends:
    - .oss_image
    - .cpu_avx
    - .build
cpu_none_oss_build:
  extends:
    - .oss_image
    - .cpu_none
    - .build
cpu_avx_gcc_oss_build:
  extends:
    - .oss_image
    - .cpu_avx_gcc
    - .build
cpu_none_gcc_oss_build:
  extends:
    - .oss_image
    - .cpu_none_gcc
    - .build

# MPI_build_test:
#   stage: build_lib
#   script:
#     - nvidia-smi
#     - make install_all
#     - cd test/mpi; make clean; make -j; make run
#   image: ${MKL_IMAGE}
#   tags:
#     - 2-gpu
#     - nvidia0-sm_61
#     - avx

