name: github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/ricosjp/allgebra/doxygen:20.10.1
    steps:
    - uses: actions/checkout@v2
    - name: doxygen
      shell: bash
      run: doxygen 
      
    - name: deploy_pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html/
        force_orphan: true
