name: github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/ricosjp/allgebra/doxygen:20.10.1
    steps:
    - uses: actions/checkout@v2
    - name: doxygen
      shell: bash
      run: |
        doxygen
        mv html public
        for version in 0.14.0 0.13.0; do
        git checkout -b tag $version
        doxygen 
        mv html public/$version
        done
      
    - name: deploy_pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/
        force_orphan: true
